language: ruby
dist: xenial
bundler_args: "--without deployment"
sudo: required
services:
- xvfb
addons:
  apt:
    packages:
    - haveged
cache:
  bundler: true
  yarn: true
  directories:
  - node_modules
env:
  global:
  - TZ=Europe/London
  - PATH=$PATH:/usr/lib/chromium-browser/
install:
- nvm install v11.14.0
- node -v
- npm i -g yarn
- yarn
- bundle install
before_script:
- bundle exec rails webpacker:verify_install
jobs:
  include:
  - name: Lint
    script:
    - bundle exec rubocop
    - yarn lint
  - stage: test
    name: Karma
    script: xvfb-run -a yarn test
  - name: RSpec
    before_script:
    - RAILS_ENV=test bundle exec rails webdrivers:chromedriver:update -r webdrivers
    script: xvfb-run -a bundle exec rspec
  - stage: build
    if: tag IS present
    name: Compile Build
    script: "./compile-build"
    deploy:
      provider: releases
      file: release.tar.gz
      file_glob: true
      skip_cleanup: true
      on:
        tags: true
        repo: sanger/limber
      api_key:
        secure: QOUG1jOoqLt1B6F7JqT/lMHp75IbnMUqKAqWj+pBnB8wYPIcT/cnTEOBGmEb0aVkIlB3wBdtitEimFNvP6FLm393GIah4wJXUHWV8HTdyKBNMyjqeV3fzKFaUTbMXxv3hX0DbLULS1YHGzQg1HMZvvpDsmouF9pGzGUhm+3OAum3GhPPfJmk+HqkiuSEx/wFPk6fN1V6+86yws14/mXS8Q5ZPoifZ3h3dcC6oFwchiGArETYwZhZsqj0Q44B+hzPHRcE3lf3qQ0HEzeWAykJn6Rl+UweAqCFGG6XcpCPs7BHXnbyEOtUQQkN9hCIrT5Lc3gKYRf/UwgK0WS+JkHoKpaXCTcLnCGiF0nbM1pPTgRXjxvVJ09qCaumpW9+Hbt7miz0gWW+ybGdZYjZPGNg0ZJVPpkd25lbsYfZkheK4miTnIndODtCzXYWLF/rqVm3Lu4vTlv7+qgpd1B9bnS2loAFEsywFhIFnKzbShvzynOypwYl1eDhHrx29JENWi9CRTHu5CGZp+VDR1kiU6eqP+A9eO5/aQNRs5qrM2ZnksmsiNYqXHNfrkZ3Pyb0aHT2FXX8VmLpzAqAIIaUWluaLh8xeaz8Ge3cm1y9FRlEwBjv9DChaDQXUyiNeRo7zAGTZOi2R5kc+4LNl1165D6v6S3/BEnYQt0g6YOl3GbYrVE=
