# WIP: Initial step of pipeline only
---
Bespoke Chromium TCR:
  filters:
    request_type_key: limber_chromium_bespoke
    library_type: Chromium single cell TCR
  relationships:
    LBC Cherrypick: LBC TCR Dil 1

